version: '2'
services:
    bootstrap:
        environment:
            - IS_BOOTSTRAP=true
            - BOOTSTRAP_NODE=127.0.0.1
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/backend-comm
        ports:
            - "9001"
            - "${BOOTSTRAP_PORT}"

    frontend:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/frontend
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
        depends_on:
            - bootstrap

    mongodb:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/mongodb
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
            - "27017"
            - "28017"
        depends_on:
            - bootstrap

    publishing:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/publishing
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
            - "27017"
            - "28017"
        depends_on:
            - bootstrap
            - mongodb

    search:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/search
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
        depends_on:
            - bootstrap
            - spell-check
            - indexer

    spell-check:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/spell-check
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
        depends_on:
            - bootstrap

    indexer:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/indexer
        ports:
            - "80"
            - "9001"
            - "5432"
            - "${BOOTSTRAP_PORT}"
        depends_on:
            - bootstrap
            - publishing

    templates:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/publishing-templates
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
            - "27017"
            - "28017"
        depends_on:
            - bootstrap

    microauth:
        environment:
            - BOOTSTRAP_NODE=${BOOTSTRAP_NODE}
            - BOOTSTRAP_PORT=${BOOTSTRAP_PORT}
        image: ${REGISTRY_URL}/microauth
        ports:
            - "80"
            - "9001"
            - "${BOOTSTRAP_PORT}"
        depends_on:
            - bootstrap
